import controls
import time


time.sleep(2)
print("Stop manual")
controls.set_motor(0, 0, 0, 0)
time.sleep(3)
# print("Forward left")
# controls.set_motor(0, 0, 0, 1)
# time.sleep(3)
# print("Backward Left")
# controls.set_motor(0, 0, 1, 0)
# time.sleep(3)
# print("Stop")
# controls.set_motor(0, 0, 0, 0)

# print("Forward right")
# controls.set_motor(0, 1, 0, 0)
# time.sleep(3)
# print("Backward right")
# controls.set_motor(1, 0, 0, 0)
# time.sleep(3)
# print("Stop")
# controls.set_motor(0, 0, 0, 0)
# time.sleep(3)
# print('exit')
#
# print("stop")
# controls.stop()
# time.sleep(3)
# print("forward")
# controls.forward()
# time.sleep(3)
# print("stop")
# controls.stop()
# time.sleep(3)
# print("reverse")
# controls.reverse()
# time.sleep(3)
